#!/usr/bin/env ansible-playbook
---
# Playbook to gather IOS Facts and configs
- hosts: ios
  gather_facts: yes
  tasks:
    - name: Gather IOS facts from {{ inventory_hostname }}
      ios_facts:
    - name: Gather show running-config from {{ inventory_hostname }}
      register: showrun_out
      ios_command:
        commands: show running-config
    - name: Gather show inventory from {{ inventory_hostname }}
      register: showinv_out
      ios_command:
        commands: show inventory
    - name: Gather show version from {{ inventory_hostname }}
      register: showver_out
      ios_command:
        commands: show version        
    - name: Write running config to reports/config/hostname.txt
      copy:
        content: "{{ showrun_out.stdout | join(' ') }}"
        dest: "reports/configs/{{ inventory_hostname }}.txt"
    - name: Write show inventory to reports/inventory/hostname.txt
      copy:
        content: "{{ showinv_out.stdout | join(' ') }}"
        dest: "reports/inventory/{{ inventory_hostname }}.txt"
    - name: Generate config report for {{ inventory_hostname }}
      local_action: template src="templates/iosconfig.j2" dest="reports/{{ inventory_hostname }}.html"
