#!/usr/bin/env ansible-playbook
---
# Playbook to configure EIGRP on multiple routers
- hosts: eigrp
  gather_facts: yes
  vars:
    interface_list:
      - GigabitEthernet2
      - Loopback27
  tasks:
#    - debug:
#        msg: "{{ hostvars[inventory_hostname] }}"
    - name: Configure interface Loopback27
      ios_config:
        parents: interface Loopback27
        lines:
          - "ip address {{ intlo27_ip }} {{ intlo27_mask }}"
          - "description {{ intlo27_desc }}"
# We don't need the facts to setup Loopback27, and we need to ansible_net_interfaces facts
# to include Loopback27. If we call ios_facts before the interface is setup, it will fail.
    - name: Gather IOS facts
      ios_facts:
    - name: Configure EIGRP
      ios_config:
        parents: "router eigrp {{ eigrp_asn }}"
        lines:
        - network {{ ansible_net_interfaces[item]['ipv4'][0]['address'] }} 0.0.0.0
      with_items: "{{ interface_list }}"
