#!/usr/bin/env ansible-playbook
---
- hosts: ios
  gather_facts: no
  tasks:
  - name: Gather IOS facts 
    ios_facts:
  - name: Configure interface GigabitEthernet2
    ios_config:
      parents: interface GigabitEthernet2
      lines:
        - "ip address {{ gig2_ip }} {{ gig2_mask }}"
        - "description {{ gig2_desc }}"
